[common]
bind_port = xxxxx
dashboard_port = xxxx
dashboard_user = "czz"
dashboard_pwd = "xxxxxx"

log_file = "./frps.log"
log_level = "info"
log_max_days = 3
token = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
heartbeat_timeout = 90
