[common]
bind_port = *****
dashboard_port = ****
dashboard_user = "czz"
dashboard_pwd = "*******"

log_file = "./frps.log"
log_level = "info"
log_max_days = 3
token = "********************************"
heartbeat_timeout = 90
